spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskmate
    username: taskmate
    password: taskmate
          
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github-client-id}
            client-secret: ${github-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read:user
              - user:email # 모든 이메일 정보를 가져오기 위한 설정
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          kakao:
            client-id: ${kakao-client-id}
#            client-secret: ${kakao-client-secret}
            client-name: Kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code

        provider:
          github:
            authorization-url: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


  jwt:
    key: dfsdfjklsf3j34324lk32l1j2312@#!@#!@#asdlksadjsalkdksajdlj2jk1j31k2j3l12kjdsaldkas@dkljaslkdjsakdjsadlksajlkdasjdlj2l13jl1k3@
    validity:
      atk: 30000000
      rtk: 30000000

  data:
    redis:
      host: localhost
      port: 6379
      # password:  (비밀번호 필요 시 추가)

  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${mail-username} # 3
    password: ${mail-password} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
frontend:
  url: ${frontend-url}
# http://localhost:8080/login/oauth2/code/google
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${CLIENT_ID}
#            client-secret: ${CLIENT_SECRET}
#            redirect-uri: http://${REDIRECT_URI_HOST}:${REDIRECT_URI_PORT}/kakao_login
#            client-authentication-method: client_secret_post
#            scope:
#              - profile_nickname
#              - account_email
#              - profile_image
#            authorization-grant-type: authorization_code
#            client-name: Kakao
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
#kakao:
#  client-id: ${CLIENT_ID}
#  client-secret: ${CLIENT_SECRET}
#  redirect-uri: http://${REDIRECT_URI_HOST}:${REDIRECT_URI_PORT}/kakao_login
#
#
#logging:
#  level:
#    org.hibernate.SQL: debug # Logger? ?? ?????? ?? SQL? ??
#    org.hibernate.orm.jdbc.bind: trace
#    com.p6spy : trace
#
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j