spring:
  datasource:
    driver-class-name: org.h2.Driver
    username : sa
    password :
    url : jdbc:h2:mem:test1

    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          trace: false
          web-allow-other: true
          
  jpa:
    hibernate:
      ddl-auto: create # ???? ???? ????
    properties:
      hibernate:
        show_sql: true # System.out ? ?????? ?? SQL? ?? => ?? ????? ???? ??? ??
        format_sql: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${CLIENT_ID}
#            client-secret: ${CLIENT_SECRET}
#            redirect-uri: http://${REDIRECT_URI_HOST}:${REDIRECT_URI_PORT}/kakao_login
#            client-authentication-method: client_secret_post
#            scope:
#              - profile_nickname
#              - account_email
#              - profile_image
#            authorization-grant-type: authorization_code
#            client-name: Kakao
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
#kakao:
#  client-id: ${CLIENT_ID}
#  client-secret: ${CLIENT_SECRET}
#  redirect-uri: http://${REDIRECT_URI_HOST}:${REDIRECT_URI_PORT}/kakao_login
#
#
#logging:
#  level:
#    org.hibernate.SQL: debug # Logger? ?? ?????? ?? SQL? ??
#    org.hibernate.orm.jdbc.bind: trace
#    com.p6spy : trace
#
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j