INSERT INTO skill_stack (category, name) VALUES
('프론트엔드', 'React'),
('프론트엔드', 'Next'),
('프론트엔드', 'RxJS'),
('프론트엔드', 'StoryBook'),
('프론트엔드', 'Styled-components'),
('프론트엔드', 'svelte'),
('프론트엔드', 'tailwind css'),
('프론트엔드', 'three js'),
('프론트엔드', 'vue js'),
('프론트엔드', 'zustand'),
('백엔드', 'Node.js'),
('백엔드', 'Express'),
('백엔드', 'NestJS'),
('백엔드', 'Python (FastAPI, Django)'),
('백엔드', 'Go'),
('백엔드', 'Java(Spring)'),
('백엔드', 'NginX'),
('백엔드', 'GraphQL'),
('백엔드', 'JWT'),
('백엔드', 'OAuth2'),
('백엔드', 'Redis'),
('백엔드', 'WebSocket'),
('데이터베이스', 'PostgreSQL'),
('데이터베이스', 'MySQL'),
('데이터베이스', 'MongoDB'),
('데이터베이스', 'Redis'),
('데이터베이스', 'Hive'),
('데이터베이스', 'BigQuery'),
('데이터베이스', 'Prisma'),
('데이터베이스', 'TypeORM'),
('클라우드', 'AWS (EC2, S3, RDS, Lambda, CloudFront, Route53)'),
('클라우드', 'GCP (Cloud Run, Firebase, BigQuery 등)'),
('클라우드', 'Docker'),
('클라우드', 'Kubernetes'),
('클라우드', 'Terraform'),
('클라우드', 'GitHub Actions'),
('클라우드', 'Vercel'),
('클라우드', 'Netlify'),
('기타 소프트웨어', 'Swagger UI (API 문서화)'),
('기타 소프트웨어', 'Postman (API 테스트)'),
('기타 소프트웨어', 'WebRTC (화상/음성 통신)'),
('기타 소프트웨어', 'Figma (디자인 협업)'),
('기타 소프트웨어', 'Jira'),
('기타 소프트웨어', 'Notion'),
('기타 소프트웨어', 'Slack'),
('기타 소프트웨어', 'Sentry'),
('기타 소프트웨어', 'LogRocket');
