version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  postgres:
    image: postgres:17
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskmate
      POSTGRES_PASSWORD: taskmate
      POSTGRES_DB: taskmate
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data