name: CI/CD Pipeline to AWS EC2

on:
  push:
    branches:
      - develop
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle wrapper 실행 권한 부여하는 단계 추가
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test


      # --------------운영 서버 배포------------------

      - name: Copy jar file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USERNAME_1 }}
          key: ${{ secrets.EC2_SSH_KEY_1 }}
          source: "build/libs/Idea-Hive-0.0.1-SNAPSHOT.jar"
          target: "~/app"
          strip_components: 2

      - name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USERNAME_1 }}
          key: ${{ secrets.EC2_SSH_KEY_1 }}
          script: |
            cd ~/app
            chmod +x deploy.sh
            ./deploy.sh

      # -------------로컬 서버 배포------------

      - name: Copy jar file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME_2 }}
          key: ${{ secrets.EC2_SSH_KEY_2 }}
          source: "build/libs/Idea-Hive-0.0.1-SNAPSHOT.jar"
          target: "~/app"
          strip_components: 2

      - name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME_2 }}
          key: ${{ secrets.EC2_SSH_KEY_2 }}
          script: |
            cd ~/app
            chmod +x deploy.sh
            ./deploy.sh